<?php

namespace backend\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "{{%address}}".
 *
 * @property integer $id
 * @property integer $user_id
 * @property string $province
 * @property string $city
 * @property string $area
 * @property string $content
 * @property string $contact
 * @property string $phone
 * @property integer $is_default
 * @property string $is_default2
 * @property string $tel_phone
 * @property string $type
 */
class Address extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%address}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_id' ,'contact'], 'required'],
            [['user_id', 'is_default', 'is_default2', 'type'], 'integer'],
            [['content'], 'string'],
            [['province', 'city', 'area', 'tel_phone'], 'string', 'max' => 50],
            [['phone'], 'string', 'max' => 20],
            [['province_id','city_id','area_id'],'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => '用户id',
            'province' => '省',
            'city' => '市',
            'area' => '区',
            'content' => '详细地址',
            'phone' => '电话',
            'is_default' => '默认地址',
            'is_default2' => '发票默认地址',
            'tel_phone' => '电话',
            'type' => 'Type',
        ];
    }


    public function beforeSave($insert)
    {


        if($this->is_default){
            if($this->is_default==1){
                Address::updateAll(['is_default'=>0],['user_id'=>$this->user_id]);
            }
        }


        if($this->province_id){
            $province=Provinces::findOne($this->province_id);
            $this->province=$province['areaname'];
        }
        if($this->city_id){
            $city=Provinces::findOne($this->city_id);
            $this->city=$city['areaname'];
        }
        if($this->area_id){
            $area=Provinces::findOne($this->area_id);
            $this->area=$area['areaname'];
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }


}
