<?php

namespace backend\models;

use common\components\CommonFunction;
use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "{{%book_detail}}".
 *
 * @property string $id
 * @property string $book_id
 * @property string $parent_id
 * @property string $title
 * @property integer $sort
 * @property string $level
 * @property string $number1
 * @property string $number2
 * @property string $content
 */
class BookDetail extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%book_detail}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['book_id', 'parent_id', 'sort', 'level', 'number1', 'number2','day'], 'integer'],
            [['content'], 'string'],
            [['title'], 'string', 'max' => 100],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'book_id' => 'Book ID',
            'parent_id' => 'Parent ID',
            'title' => '名称',
            'sort' => '排序',
            'level' => 'Level',
            'number1' => '章',
            'number2' => '节',
            'content' => '内容',
            'day'=>'第几天阅读'
        ];
    }

    public function beforeSave($insert)
    {

        if($this->number2==0){
            $this->level=1;
        }else{
            $parent=BookDetail::find()->where(['number1'=>$this->number1,'number2'=>0])->limit(1)->one();
            if($parent){
                $this->parent_id=$parent->id;
            }
            $this->level=2;
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

}
