<?php

namespace backend\models;

use common\components\CommonFunction;
use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "{{%company}}".
 *
 * @property string $id
 * @property string $title
 * @property string $name
 * @property string $industry
 * @property string $info
 * @property string $content
 * @property integer $sort
 * @property string $image
 * @property string $created_at
 * @property string $updated_at
 */
class Company extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%company}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['info', 'content'], 'string'],
            [['sort'], 'integer'],
            [['title', 'name'], 'string', 'max' => 100],
            [['image'], 'string', 'max' => 255],
            [['industry'],'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => '公司名称',
            'name' => '负责人',
            'industry' => '行业',
            'info' => '公司简介',
            'content' => '主营业务',
            'sort' => '排序',
            'image' => '图片',
            'created_at' => '添加时间',
            'updated_at' => 'Updated At',
        ];
    }

    /**
    * @return array
    */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['created_at', 'updated_at'],
                    ActiveRecord::EVENT_BEFORE_UPDATE => ['updated_at'],
                ],
            ],
        ];
    }

    public function beforeSave($insert)
    {

        if(is_array($this->industry)){
            $this->industry=implode(',',$this->industry);
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
