<?php

namespace backend\models;

use common\components\CommonFunction;
use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "{{%douyin}}".
 *
 * @property string $id
 * @property string $title
 * @property string $image
 * @property string $status
 * @property string $created_at
 */
class Douyin extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%douyin}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['status', 'created_at'], 'integer'],
            [['title', 'image'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => '抖音号',
            'image' => '图片',
            'status' => '状态',
            'created_at' => '添加时间',
        ];
    }



    public function beforeSave($insert)
    {

        if($this->image){
            $this->image=CommonFunction::unsetImg($this->image);
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

}
