<?php

namespace backend\models;

use common\components\CommonFunction;
use common\components\Helper;
use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "zs_news".
 *
 * @property string $id
 * @property string $title
 * @property string $type
 * @property integer $sort
 * @property integer $is_html
 * @property string $hit
 * @property string $image
 * @property string $content
 * @property string $created_at
 * @property string $updated_at
 * @property string $language
 * @property string $is_news
 */
class News extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'zs_news';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['type', 'sort', 'is_html', 'hit', 'is_news'], 'integer'],
            [['content'], 'string'],
            [['title', 'image'], 'string', 'max' => 255],
            [['language'], 'string', 'max' => 50],
            [['subtitle'],'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => '标题',
            'type' => 'Type',
            'sort' => '排序',
            'is_html' => 'Is Html',
            'hit' => '阅读量',
            'image' => '图片',
            'content' => '内容',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'language' => 'Language',
            'is_news' => 'Is News',

        ];
    }

    /**
    * @return array
    */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['created_at', 'updated_at'],
                    ActiveRecord::EVENT_BEFORE_UPDATE => ['updated_at'],
                ],
            ],
        ];
    }



    public function beforeSave($insert)
    {

        if($this->image){
            $this->image=CommonFunction::unsetImg($this->image);
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
