<?php

namespace backend\models;

use common\components\CommonFunction;
use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "{{%practice_category}}".
 *
 * @property string $id
 * @property string $title
 * @property integer $level
 * @property string $sort
 * @property string $image
 * @property string $parent_id
 * @property string $type
 */
class PracticeCategory extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%practice_category}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['level', 'sort', 'parent_id', 'type'], 'integer'],
            [['title'], 'string', 'max' => 100],
            [['image'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => '名称',
            'level' => '等级',
            'sort' => '排序',
            'image' => '图片',
            'parent_id' => '上级',
            'type' => '类型',
        ];
    }

    //关联下级

    public function getChildren()

    {

        return $this->hasMany(PracticeCategory::class, ['parent_id' => 'id']);

    }

    public static function getList(){
        $model=PracticeCategory::find()->select(['id','title'])->orderBy('level asc,sort asc,id desc')->asArray()->all();
        return ArrayHelper::map($model,'id','title');
    }


    public function beforeSave($insert)
    {

        if($this->image){
            $this->image=CommonFunction::unsetImg($this->image);
        }


        if($this->parent_id>0){
            $parent=PracticeCategory::findOne($this->parent_id);
            if($parent and $parent->type==1 and $parent->parent_id==0){
                $parent->type=2;
                $parent->save();
            }
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

}
