<?php

namespace backend\models;

use common\components\CommonFunction;
use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "{{%server}}".
 *
 * @property integer $id
 * @property string $title
 * @property string $type
 * @property string $value
 * @property string $image
 */
class Server extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%server}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['type','sort'], 'integer'],
            [['title'], 'string', 'max' => 50],
            [['value', 'image'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => '名称',
            'type' => '类型',
            'value' => '内容',
            'image' => '图片',
        ];
    }

    public function beforeSave($insert)
    {

        if($this->image){
            $this->image=CommonFunction::unsetImg($this->image);
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
