<?php

namespace backend\models;

use common\components\CommonFunction;
use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "{{%task_user}}".
 *
 * @property string $id
 * @property string $user_id
 * @property string $task_id
 * @property string $created_at
 * @property string $updated_at
 */
class TaskUser extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%task_user}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_id', 'task_id'], 'integer'],
            [['image','file'],'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => '用户',
            'task_id' => '课程',
            'created_at' => '添加时间',
            'image' => '图片',
            'file'=>'音频文件',
            'updated_at' => 'Updated At',
            'content'=>'内容'
        ];
    }

    /**
    * @return array
    */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['created_at', 'updated_at'],
                    ActiveRecord::EVENT_BEFORE_UPDATE => ['updated_at'],
                ],
            ],
        ];
    }

    public function beforeSave($insert)
    {

        if($this->file){
            $this->file=CommonFunction::unsetImg($this->file);
        }
        if($this->image){
            $arr_value=[];
            $arr=explode(',',$this->image);
            foreach ($arr as $k=>$v){
                $arr_value[]=CommonFunction::unsetImg($v);
            }
            $this->image=implode(',',$arr_value);
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }


    public function getUser(){
        return $this->hasOne(User::class,['id'=>'user_id']);
    }

    public function getTask(){
        return $this->hasOne(Task::class,['id'=>'task_id']);
    }
}
