<?php

namespace backend\models;

use common\components\CommonFunction;
use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "{{%task}}".
 *
 * @property string $id
 * @property string $image
 * @property string $video
 * @property string $title
 * @property string $start_time
 * @property string $end_time
 * @property integer $sort
 * @property string $created_at
 * @property string $updated_at
 */
class Task extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%task}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['sort'], 'integer'],
            [['image', 'video'], 'string', 'max' => 255],
            [['title'], 'string', 'max' => 100],
            [['start_time','end_time','type'],'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'image' => '图片',
            'video' => '视频',
            'title' => '标题',
            'start_time' => '开始时间',
            'end_time' => '结束时间',
            'sort' => '排序',
            'created_at' => '添加时间',
            'updated_at' => 'Updated At',
            'type'=>'类型'
        ];
    }

    /**
    * @return array
    */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['created_at', 'updated_at'],
                    ActiveRecord::EVENT_BEFORE_UPDATE => ['updated_at'],
                ],
            ],
        ];
    }

    public function beforeSave($insert)
    {

        if($this->image){
            $this->image=CommonFunction::unsetImg($this->image);
        }
        if(!is_numeric($this->start_time)){
            $this->start_time=strtotime($this->start_time);
        }
        if(!is_numeric($this->end_time)){
            $this->end_time=strtotime($this->end_time);
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }



    public static function getList()
    {
        $model = self::find()->orderBy('id asc')->asArray()->all();
        return ArrayHelper::map($model, 'id', 'title');
    }
}
